#!/bin/bash

source_path=~/.tmux/plugins/tmux-git-prompt/git-prompt.sh
if [[ ! -f ${source_path} ]]; then
  curl -sL https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh > ${source_path}
fi
source ${source_path} &>/dev/null

export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM="auto"
export GIT_PS1_DESCRIBE_STYLE="branch"
export GIT_PS1_SHOWCOLORHINTS=0

dir=${1}
if [[ ! -d ${dir}/.git ]]; then
  exit 0
fi

cd "${dir}"
worktree="$(__git_ps1 "%s" 2>/dev/null)"
if [[ -n ${worktree} ]]; then
  echo ${worktree}
fi
