#!/bin/bash

source ~/.tmux/plugins/tmux-git-prompt/git-prompt.sh &>/dev/null

export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM="auto"
export GIT_PS1_DESCRIBE_STYLE="branch"
export GIT_PS1_SHOWCOLORHINTS=0

dir=${1}
if [[ ! -d ${dir}/.git ]]; then
  exit 0
fi

cd "${dir}"
worktree="$(__git_ps1 "%s" 2>/dev/null)"
if [[ -n ${worktree} ]]; then
  echo ${worktree}
fi
